In [85]:
import pandas as pd
df_bean = pd.read_csv('F:/University_HCMUTE/N3_HK2/AIOT/GiuaKy/Dry_Beans_Dataset.csv')
df_bean

Area  Perimeter  MajorAxisLength  MinorAxisLength  AspectRation  \
0      28395    610.291       208.178117       173.888747      1.197191   
1      28734    638.018       200.524796       182.734419      1.097356   
2      29380    624.110       212.826130       175.931143      1.209713   
3      30008    645.884       210.557999       182.516516      1.153638   
4      30140    620.134       201.847882       190.279279      1.060798   
...      ...        ...              ...              ...           ...   
13606  42097    759.696       288.721612       185.944705      1.552728   
13607  42101    757.499       281.576392       190.713136      1.476439   
13608  42139    759.321       281.539928       191.187979      1.472582   
13609  42147    763.779       283.382636       190.275731      1.489326   
13610  42159    772.237       295.142741       182.204716      1.619841   

       Eccentricity  ConvexArea  EquivDiameter    Extent  Solidity  roundness  \
0          0.549812       28715     190.141097  0.763923  0.988856   0.958027   
1          0.411785       29172     191.272751  0.783968  0.984986   0.887034   
2          0.562727       29690     193.410904  0.778113  0.989559   0.947849   
3          0.498616       30724     195.467062  0.782681  0.976696   0.903936   
4          0.333680       30417     195.896503  0.773098  0.990893   0.984877   
...             ...         ...            ...       ...       ...        ...   
13606      0.765002       42508     231.515799  0.714574  0.990331   0.916603   
13607      0.735702       42494     231.526798  0.799943  0.990752   0.922015   
13608      0.734065       42569     231.631261  0.729932  0.989899   0.918424   
13609      0.741055       42667     231.653247  0.705389  0.987813   0.907906   
13610      0.786693       42600     231.686223  0.788962  0.989648   0.888380   

       Compactness  ShapeFactor1  ShapeFactor2  ShapeFactor3  ShapeFactor4  \
0         0.913358      0.007332      0.003147      0.834222      0.998724   
1         0.953861      0.006979      0.003564      0.909851      0.998430   
2         0.908774      0.007244      0.003048      0.825871      0.999066   
3         0.928329      0.007017      0.003215      0.861794      0.994199   
4         0.970516      0.006697      0.003665      0.941900      0.999166   
...            ...           ...           ...           ...           ...   
13606     0.801865      0.006858      0.001749      0.642988      0.998385   
13607     0.822252      0.006688      0.001886      0.676099      0.998219   
13608     0.822730      0.006681      0.001888      0.676884      0.996767   
13609     0.817457      0.006724      0.001852      0.668237      0.995222   
13610     0.784997      0.007001      0.001640      0.616221      0.998180   

          Class  
0         SEKER  
1         SEKER  
2         SEKER  
3         SEKER  
4         SEKER  
...         ...  
13606  DERMASON  
13607  DERMASON  
13608  DERMASON  
13609  DERMASON  
13610  DERMASON  

[13611 rows x 17 columns]

In [86]:
df_bean.Class = df_bean['Class'].map({'SEKER': 0, 'BARBUNYA': 1, 'BOMBAY': 2, 'CALI': 3, 'HOROZ': 4, 'SIRA': 5, 'DERMASON': 6})


In [87]:
goal_bean = df_bean['Class']
data_bean = df_bean.drop('Class', axis=1)

In [88]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
scaler = StandardScaler()

data_bean = scaler.fit_transform(data_bean)
x_train, x_test, y_train, y_test = train_test_split(data_bean, goal_bean, test_size=0.2)

Model Logistic Regression Mutilnomial

In [89]:
import numpy as np

def softmax(z):
    z -= np.max(z, axis=1, keepdims=True)
    exp_sum = np.sum(np.exp(z), axis=1, keepdims=True)
    return np.exp(z) / exp_sum



In [90]:
def one_hot_label(labels, num_classes):
    return np.eye(num_classes)[labels]


In [91]:
print(y_test)
y_one_hot = one_hot_label(y_test, 7)
print(y_one_hot)

12224    6
5212     3
13374    6
5680     4
1890     0
        ..
10793    6
914      0
5840     4
6593     4
9725     5
Name: Class, Length: 2723, dtype: int64
[[0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]]


In [92]:
def predict(features, weights):
    fc = np.dot(features, weights.T)
    return softmax(fc)

In [93]:
def gradient_descent(features, labels, weights, learning_rate):
    mu_i = predict(features, weights)
    y_i = one_hot_label(labels, len(weights))
    weights = weights - learning_rate * np.dot((mu_i - y_i).T, features)
    return weights

In [94]:
def train(features, labels, num_classes, learning_rate, iter):
    num_features = features.shape[1]
    weights = np.zeros((num_classes, num_features))  
    for i in range(iter):
        weights = gradient_descent(features, labels, weights, learning_rate)
    return weights

In [95]:
value_unique =  len(np.unique(y_test))
w = train(x_train, y_train, value_unique, learning_rate = 0.01, iter= 5000)

In [96]:
print(w)

[[-21.66589945   8.61279108   9.3386126  -30.98909909  30.62302761
  -53.33909321 -20.81544894  -9.96607696  -2.87828271  10.57553479
   -8.70333407 -12.00567278 -62.32538336  10.52368142  -2.13714249
   17.28802347]
 [ -0.16190752   3.66870356 -25.44141869  37.81127865 -15.67862579
  -21.41698445   1.97476477   3.87351356   1.70549756  -7.66111433
   -9.59676249   3.17927162   9.43651715 -69.86717449   1.03568105
    8.10662472]
 [ 88.21997172   0.48661749  -6.73894373  19.59447159  -6.23871914
    3.54602549  89.62220279   4.29151277   4.17501275  -9.96433173
   23.43762871   8.49293392 107.09225455  22.06897149   8.05455951
    8.75530377]
 [ -5.0980132   -1.89556048  30.16594419   1.78189747 -25.85173101
   21.46002879  -6.27911822  21.40756588   2.00873723  -3.11506171
    6.27850884  -7.52242852 -23.66800951  16.89105555 -13.53906277
   -5.64724961]
 [-22.86675668  27.12743655   2.0004242  -18.43561287  45.08040134
  -16.34246366 -20.08667198 -14.2764909   -0.40376458   5.2248901

In [101]:
from sklearn.metrics import accuracy_score
bean_pred = predict(x_test, w)
bean_pred = np.argmax(bean_pred, axis = 1)
act = accuracy_score(y_test, bean_pred)
print(act)

0.9114946749908189


In [98]:
from sklearn.metrics import confusion_matrix
conf_matrix = confusion_matrix(y_test, bean_pred)
print(conf_matrix)

[[405   0   0   1   0   8  11]
 [  2 241   0  18   1   5   0]
 [  0   0 102   0   0   0   0]
 [  2  10   2 303   3   3   0]
 [  0   1   0   7 353  23   6]
 [ 14   0   0   2   1 408  94]
 [  6   0   0   0   4  17 670]]


In [102]:
from sklearn.linear_model import LogisticRegression
model_bean = LogisticRegression(max_iter=5000, multi_class='multinomial')
model_bean.fit(x_train, y_train)

LogisticRegression(max_iter=5000, multi_class='multinomial')

In [103]:
y4_pred = model_bean.predict(x_test)
act = accuracy_score(y_test, y4_pred)
print(act)

0.9272860815277267


In [76]:
conf_matrix = confusion_matrix(y_test, y4_pred)
print(conf_matrix)

[[403   4   0   0   1  16   4]
 [  1 238   0  14   0   5   0]
 [  0   0  92   0   0   0   0]
 [  0   7   0 289   5   6   0]
 [  0   1   0   9 370   6   6]
 [  7   0   0   2   8 444  61]
 [ 11   0   0   0   2  50 661]]


Test email spam

In [77]:
df_email = pd.read_csv("F:/University_HCMUTE/N3_HK2/AIOT/GiuaKy/emails.csv")
goal = df_email.Prediction
data = df_email.drop(['Prediction', 'Email No.'], axis='columns')
x1, x2, y1, y2 = train_test_split(data, goal, test_size=0.2)

In [78]:
value_unique =  len(np.unique(y2))
w_email = train(x1, y1, 2, learning_rate= 0.01, iter=1000)

In [79]:
print(w_email)

[[ 3311.40264502  3244.55933914  3541.01050278 ...    11.90501408
   -244.76516367    24.58318136]
 [-3311.40264502 -3244.55933914 -3541.01050278 ...   -11.90501408
    244.76516367   -24.58318136]]


In [80]:
y_pred_email = predict(x2, w_email)
y_pred_email = np.argmax(y_pred_email, axis=1)

In [81]:
act = accuracy_score(y2, y_pred_email)
print(act)

0.8995169082125604


In [82]:
def split_email(email_input):
    email_array = np.zeros(3000)
    words = email_input.split(' ')
    for word in words:
        word = word.lower()
        if word in data.columns:
            index = data.columns.get_loc(word) #lay vi tri cot co tu do
            email_array[index] += 1
    email_array = email_array.reshape(1, -1)
    return email_array

In [83]:
email_content = "I think Donk is insanely talented for his age but he needs to be more mature"
email_features = split_email(email_content)
email_pred = predict(email_features, w_email)

In [84]:
email_pred = predict(email_features, w_email)
email_pred = np.argmax(email_pred, axis=1)
# In kết quả dự đoán
if email_pred >= 0.5:
    print("Email này được dự đoán là spam.")
else:
    print("Email này được dự đoán là không spam.")

Email này được dự đoán là không spam.
